#!/bin/bash
echo "******************************************************************************************";
echo "** welcome to my projet sys:  VANDI KOYANG JOSEPH 13A534FS                             ***";
echo "**veilleez taper une lettre qui correspond a une operation                             ***";
echo "**a- les informtions sur les utilisteur qui sont enregistees                           ***";
echo "**b- acquisition, installation et lancement de l'environement xampp                    ***";
echo "**c- archivage de repertoire personnel                                                 ***";
echo "**d- information sur l,utlisation du disque,de la memoire, du processeur et de la swaps **";
echo "**Q- pour quiter le programme                                                          ***";
echo "******************************************************************************************";
 read x;
     while (test $x != q)
     do
       echo "vous avez entree " $x;
         if(test $x = a) then
            echo "Veuillez patienter SVP";
            echo "les informations des utilisateurs";
            ls -lth /home;
          else
              if(test $x = b)then
                 echo "debut du telechargement du xampp";
                 sudo wget https:www.apachefriends.org/fr/download_success.html/xampp-linux-x64-5.6.30-1-installer.run;
                 echo " installation de l'environement xampp ";
                 sudo chmod xampp-linux-x64-5.6.30-1-installer.run;
                 sudo ./xampp-linux-x64-5.6.30-1installer.run;
                 echo " lencement de xampp";
                 sudo /lamp/lamp start;
               else
                  if(test $x = c)then
                     echo " Veuillez patienter svp";
                     sudo find . -ctime -2>fichier1 | tar cvf fichier1.tar fichier1;
                  else
                      if(test $x = d) then
                         echo "voici les informations liees a la memoire, au processeur et la swaps";
                          df -h; top | head -6
                      else
                          echo "Veillez entrer une lettre autorisee";
                     fi
                 fi
               fi
           fi
           echo " entrer la lettre pour continuer";
           read x;
       done

